extends RefCounted

static func defs(core_size: Vector2i) -> Dictionary:
	return {
		"core": {"name": "Core", "size": core_size, "cost": {}, "category": "misc", "power_storage": 100.0},
		"conveyor": {"name": "Conveyor", "size": Vector2i(1, 1), "cost": {"copper": 1}, "category": "belts", "belt_speed": 2.6},
		"fast_conveyor": {"name": "Fast Conveyor", "size": Vector2i(1, 1), "cost": {"copper": 2, "lead": 1}, "category": "belts", "belt_speed": 3.5},
		"titan_conveyor": {"name": "Titan Conveyor", "size": Vector2i(1, 1), "cost": {"lead": 2, "titanium": 1}, "category": "belts", "belt_speed": 4.5},
		"thorium_conveyor": {"name": "Thorium Conveyor", "size": Vector2i(1, 1), "cost": {"lead": 3, "thorium": 1}, "category": "belts", "belt_speed": 5.8},
		"cross": {"name": "Crossing", "size": Vector2i(1, 1), "cost": {"copper": 2}, "category": "belts"},
		"drill": {"name": "Drill", "size": Vector2i(1, 1), "cost": {"copper": 12}, "category": "drills", "mine_tier": 1, "drill_time": 1.45, "accepts_water": true},
		"rotary_drill": {"name": "Rotary Drill", "size": Vector2i(1, 1), "cost": {"copper": 18, "lead": 8}, "category": "drills", "mine_tier": 2, "drill_time": 1.0, "accepts_water": true},
		"impact_drill": {"name": "Impact Drill", "size": Vector2i(1, 1), "cost": {"copper": 22, "lead": 12, "graphite": 6}, "category": "drills", "mine_tier": 3, "drill_time": 0.75, "accepts_water": true, "power_consumption": 45.0},
		"blast_drill": {"name": "Blast Drill", "size": Vector2i(1, 1), "cost": {"lead": 18, "titanium": 8, "thorium": 5}, "category": "drills", "mine_tier": 4, "drill_time": 0.55, "accepts_water": true, "power_consumption": 90.0},
		"wall": {"name": "Wall", "size": Vector2i(1, 1), "cost": {"copper": 4}, "category": "walls"},
		"titanium_wall": {"name": "Titanium Wall", "size": Vector2i(1, 1), "cost": {"titanium": 6}, "category": "walls"},
		"plastinium_wall": {"name": "Plastinium Wall", "size": Vector2i(1, 1), "cost": {"plastinium": 5, "titanium": 2}, "category": "walls"},
		"turret": {"name": "Turret", "size": Vector2i(1, 1), "cost": {"copper": 30, "graphite": 2}, "category": "turrets", "ammo_turret": true, "turret_range": 210.0, "turret_reload": 0.55, "damage_copper": 28.0, "damage_graphite": 55.0, "turret_bullet_speed": 460.0, "turret_spread": 0.0, "accepts_water": true},
		"scatter_tower": {"name": "Scatter Tower", "size": Vector2i(1, 1), "cost": {"copper": 28, "lead": 16, "graphite": 6}, "category": "turrets", "ammo_turret": true, "turret_range": 195.0, "turret_reload": 0.34, "damage_copper": 15.0, "damage_graphite": 30.0, "turret_bullet_speed": 420.0, "turret_spread": 0.2, "accepts_water": true},
		"lightning_turret": {"name": "Lightning Turret", "size": Vector2i(1, 1), "cost": {"copper": 40, "graphite": 12}, "category": "turrets", "power_consumption": 90.0},
		"rail_tower": {"name": "Rail Tower", "size": Vector2i(1, 1), "cost": {"lead": 20, "titanium": 12, "graphite": 10}, "category": "turrets", "ammo_turret": true, "turret_range": 310.0, "turret_reload": 1.15, "damage_copper": 60.0, "damage_graphite": 105.0, "turret_bullet_speed": 650.0, "turret_spread": 0.02, "accepts_water": true},
		"hail_turret": {"name": "Hail Turret", "size": Vector2i(1, 1), "cost": {"copper": 35, "graphite": 8}, "category": "turrets", "ammo_turret": true, "ammo_types": ["copper", "graphite", "pyrite"], "turret_range": 360.0, "turret_reload": 1.45, "damage_copper": 42.0, "damage_graphite": 76.0, "damage_pyrite": 95.0, "turret_bullet_speed": 520.0, "turret_spread": 0.04, "accepts_water": true},
		"wave_turret": {"name": "Wave Turret", "size": Vector2i(1, 1), "cost": {"lead": 25, "graphite": 10}, "category": "turrets", "fluid_turret": true, "accepts_liquids": ["water", "oil"], "turret_range": 190.0, "turret_reload": 0.7, "damage_water": 18.0, "damage_oil": 26.0, "turret_bullet_speed": 390.0, "turret_spread": 0.1},
		"beam_turret": {"name": "Beam Turret", "size": Vector2i(2, 2), "cost": {"silicon": 35, "titanium": 18, "graphite": 14}, "category": "turrets", "power_turret": true, "power_consumption": 110.0, "turret_range": 285.0, "turret_reload": 0.85, "damage_power": 72.0, "turret_bullet_speed": 760.0, "turret_spread": 0.0},
		"salvo_turret": {"name": "Salvo Turret", "size": Vector2i(2, 2), "cost": {"copper": 60, "graphite": 18, "silicon": 10}, "category": "turrets", "ammo_turret": true, "ammo_types": ["copper", "graphite", "pyrite"], "turret_range": 235.0, "turret_reload": 0.18, "damage_copper": 17.0, "damage_graphite": 30.0, "damage_pyrite": 40.0, "turret_bullet_speed": 500.0, "turret_spread": 0.12, "accepts_water": true},
		"ripple_turret": {"name": "Ripple Turret", "size": Vector2i(3, 3), "cost": {"lead": 80, "titanium": 35, "silicon": 20}, "category": "turrets", "ammo_turret": true, "ammo_types": ["graphite", "pyrite"], "turret_range": 430.0, "turret_reload": 1.8, "damage_graphite": 130.0, "damage_pyrite": 170.0, "turret_bullet_speed": 360.0, "turret_spread": 0.18, "accepts_water": true},
		"generator": {"name": "Burner", "size": Vector2i(2, 2), "cost": {"copper": 35, "coal": 8}, "category": "power", "power_production": 60.0, "requires_fuel": true},
		"magmatic_generator": {"name": "Magmatic Generator", "size": Vector2i(2, 2), "cost": {"copper": 45, "lead": 18, "graphite": 8}, "category": "power", "power_production": 120.0, "place_on": "magma"},
		"node": {"name": "Power Node", "size": Vector2i(1, 1), "cost": {"copper": 8}, "category": "power"},
		"battery": {"name": "Battery", "size": Vector2i(1, 1), "cost": {"copper": 20, "graphite": 4}, "category": "power", "power_storage": 100.0},
		"press": {"name": "Graphite Press", "size": Vector2i(2, 2), "cost": {"copper": 45, "coal": 6}, "category": "factories", "factory_recipe": {"input": "coal", "input_amount": 2, "output": "graphite", "output_amount": 1, "craft_time": 1.8}},
		"carbon_refinery": {"name": "Carbon Refinery", "size": Vector2i(2, 2), "cost": {"lead": 20, "titanium": 10, "graphite": 8}, "category": "factories", "power_consumption": 60.0, "factory_recipe": {"input": "coal", "input_amount": 2, "output": "graphite", "output_amount": 2, "craft_time": 1.6}},
		"silicon_smelter": {"name": "Silicon Smelter", "size": Vector2i(2, 2), "cost": {"copper": 50, "lead": 25, "graphite": 8}, "category": "factories", "power_consumption": 50.0, "factory_recipe": {"inputs": {"coal": 1, "sand": 1}, "output": "silicon", "output_amount": 1, "craft_time": 1.4}},
		"pyrite_mixer": {"name": "Pyrite Mixer", "size": Vector2i(2, 2), "cost": {"lead": 35, "graphite": 12}, "category": "factories", "factory_recipe": {"inputs": {"coal": 1, "lead": 1, "sand": 1}, "output": "pyrite", "output_amount": 1, "craft_time": 1.7}},
		"plastinium_compressor": {"name": "Plastinium Compressor", "size": Vector2i(2, 2), "cost": {"lead": 45, "titanium": 30, "silicon": 12}, "category": "factories", "power_consumption": 80.0, "factory_recipe": {"inputs": {"titanium": 2}, "liquid_input": {"kind": "oil", "amount": 1}, "output": "plastinium", "output_amount": 1, "craft_time": 2.0}},
		"oil_extractor": {"name": "Oil Extractor", "size": Vector2i(2, 2), "cost": {"lead": 35, "graphite": 16, "silicon": 8}, "category": "fluids", "place_on": "sand", "fluid_output": "oil", "fluid_interval": 0.7},
		"pump": {"name": "Pump", "size": Vector2i(1, 1), "cost": {"copper": 15}, "category": "fluids", "place_on": "water", "fluid_output": "water", "fluid_interval": 0.6},
		"powered_pump": {"name": "Powered Pump", "size": Vector2i(1, 1), "cost": {"lead": 18, "graphite": 6}, "category": "fluids", "place_on": "water", "power_consumption": 30.0, "fluid_output": "water", "fluid_interval": 0.3},
		"pipe": {"name": "Pipe", "size": Vector2i(1, 1), "cost": {"copper": 1}, "category": "fluids"},
		"xp_sink": {"name": "XP Sink", "size": Vector2i(2, 2), "cost": {"copper": 40, "graphite": 6}, "category": "combat", "power_consumption": 30.0, "xp_sink": true, "xp_rate": 4.0, "xp_rate_powered": 10.0},
		"resource_depot": {"name": "Resource Depot", "size": Vector2i(2, 2), "cost": {"copper": 35, "lead": 10}, "category": "combat", "power_consumption": 30.0, "depot": true, "depot_range": 150.0, "depot_rate": 6.0, "depot_rate_powered": 14.0}
	}

static func health(core_health: float) -> Dictionary:
	return {
		"core": core_health,
		"conveyor": 45.0,
		"fast_conveyor": 50.0,
		"titan_conveyor": 55.0,
		"thorium_conveyor": 60.0,
		"cross": 55.0,
		"drill": 90.0,
		"rotary_drill": 120.0,
		"impact_drill": 155.0,
		"blast_drill": 190.0,
		"wall": 220.0,
		"titanium_wall": 520.0,
		"plastinium_wall": 760.0,
		"turret": 150.0,
		"scatter_tower": 165.0,
		"lightning_turret": 160.0,
		"rail_tower": 190.0,
		"hail_turret": 170.0,
		"wave_turret": 175.0,
		"beam_turret": 230.0,
		"salvo_turret": 240.0,
		"ripple_turret": 320.0,
		"generator": 180.0,
		"magmatic_generator": 260.0,
		"node": 70.0,
		"battery": 110.0,
		"press": 170.0,
		"carbon_refinery": 210.0,
		"silicon_smelter": 190.0,
		"pyrite_mixer": 180.0,
		"plastinium_compressor": 230.0,
		"oil_extractor": 170.0,
		"pump": 80.0,
		"powered_pump": 110.0,
		"pipe": 45.0,
		"xp_sink": 180.0,
		"resource_depot": 170.0
	}
